trigger:
- master

stages:
- stage: Exploring_the_agent
  pool:
    vmImage: ubuntu-latest

jobs:
- job: checking_user_and_working_directory
  steps:
  - script: pwd
    displayName:"show current working directory"

  - script: whoami
    displayName: "check current user"
- job: printing_funny_messages
  steps:
  - script: sudo apt-get install cowsay
  displayName:"install cowsay for dispalying messages"
